name: flutter_messanger_ui
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  font_awesome_flutter: ^11.0.0
  flutter_secure_storage: ^10.2.0
  flutter_chat_core: ^2.0.0
  flutter_chat_ui: ^2.0.0
  flutter_chat_types: ^3.6.2
  mask_text_input_formatter: ^2.9.0
  window_manager: ^0.5.1
  shared_preferences: ^2.3.0
  file_picker: ^8.0.0
  pro_image_editor: ^12.4.4
  flutter_distributor: ^0.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true